remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Documentation
description: # Table of contents

- [accordion](#accordion)
- [accordion-group](#accordion-group)
- [animations](#animations)
- [announcement-bar](#announcement-bar)
- [back-to-top-button](#back-to-top-button)
- [interactive-cart](#interactive-cart)
- [cart-items](#cart-items)
- [cart-item](#cart-item)
- [discount-list](#discount-list)
- [cart-text-input](#cart-text-input)
- [cart-gift-wrapping-message](#cart-gift-wrapping-message)
- [cart-note](#cart-note)
- [cart-terms](#cart-terms)
- [cart-notification](#cart-notification)
- [cart-quantity-info](#cart-quantity-info)
- [cart-gift-wrapping-banner](#cart-gift-wrapping-banner)
- [free-shipping-bar](#free-shipping-bar)
- [cart-link](#cart-link)
- [cart-recommendations](#cart-recommendations)
- [cart-store](#cart-store)
- [deferred-media](#deferred-media)
- [details-disclosure](#details-disclosure)
- [drawer-menu](#drawer-menu)
- [dynamic-button](#dynamic-button)
- [dynamic-product-search](#dynamic-product-search)
- [filters-dialog](#filters-dialog)
- [gift-card-recipient](#gift-card-recipient)
- [header-container](#header-container)
- [header-details-disclosure](#header-details-disclosure)
- [image-compare](#image-compare)
- [image-skeleton](#image-skeleton)
- [interactive-map](#interactive-map)
- [items-scroll](#items-scroll)
- [lazy-video](#lazy-video)
- [localize-details-disclosure](#localize-details-disclosure)
- [maps-with-details](#maps-with-details)
- [media-carousel](#media-carousel)
- [media-gallery](#media-gallery)
- [modal-dialog](#modal-dialog)
- [nested-menu](#nested-menu)
- [pickup-availability](#pickup-availability)
- [popup-dialog](#popup-dialog)
- [predictive-search](#predictive-search)
- [price-range](#price-range)
- [product-card-spinner](#product-card-spinner)
- [product-card-swatches](#product-card-swatches)
- [product-card-mini](#product-card-mini)
- [product-card](#product-card)
- [product-form](#product-form)
- [product-interactive-options](#product-interactive-options)
- [product-model](#product-model)
- [product-recommendations](#product-recommendations)
- [product-single](#product-single)
- [quantity-input](#quantity-input)
- [quick-shop](#quick-shop)
- [recent-searches](#recent-searches)
- [scroll-to-target](#scroll-to-target)
- [scrolling-marquee](#scrolling-marquee)
- [search-form](#search-form)
- [search-modal](#search-modal)
- [staged-action](#staged-action)
- [sticky-scroll](#sticky-scroll)
- [tabbed-content](#tabbed-content)
- [tab-triggers](#tab-triggers)
- [variant-selects](#variant-selects)
- [variant-radios](#variant-radios)
- [variant-swatches](#variant-swatches)
- [variant-mixed-inputs](#variant-mixed-inputs)
- [video-dialog](#video-dialog)
- [video-gallery](#video-gallery)
- [video-gallery-thumbnail](#video-gallery-thumbnail)
- [video-player](#video-player)